USE COMERCIO;

SELECT GETDATE();

INSERT PRODUTOS VALUES(1, 'Nome do meu produto', GETDATE(), '1234567890', 0);

SELECT TOP (100) [CODIGO], [DESCRICAO], [DATA_VALIDADE], [EAN], [IND_INATIVO] FROM PRODUTOS;

INSERT PRODUTOS VALUES(1, 'Nome do produto 2', GETDATE(), '2348322435', 0);
INSERT PRODUTOS VALUES(2, 'Nome do produto 2', GETDATE(), '2348322435', 0);

INSERT INTO PRODUTOS(CODIGO, DESCRICAO, EAN) VALUES(3, 'Nome do produto 3', '2348695043');

SELECT * FROM PRODUTOS;

SELECT * FROM PRODUTOS WHERE CODIGO = 3;

SELECT * FROM PRODUTOS WHERE DESCRICAO LIKE '%produto';

SELECT convert(varchar, GETDATE(),101);

SELECT convert(varchar, GETDATE(),101) AS 'DATA DE VALIDADE';

SELECT COUNT(*) AS 'TOTAL DE PRODUTOS NO BANCO' FROM PRODUTOS;
