CREATE DATABASE COMERCIO;

USE COMERCIO;

CREATE TABLE PRODUTOS(
	CODIGO INT NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL,
	DATA_VALIDADE DATETIME,
	EAN VARCHAR(15) NOT NULL, -- EAN É UM CÓDIGO DE BARRAS
	IND_INATIVO INT NOT NULL DEFAULT 0
);

ALTER TABLE PRODUTOS
	ADD CONSTRAINT PK_PRODUTOS
		PRIMARY KEY (CODIGO)
;

INSERT PRODUTOS VALUES(1, 'Nome do meu produto', GETDATE(), '1234567890', 0);

SELECT TOP (100) [CODIGO], [DESCRICAO], [DATA_VALIDADE], [EAN], [IND_INATIVO] FROM PRODUTOS;

SELECT GETDATE();